### ISSUE TITLE
Type check BIR

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1169] opened 2023-02-20 10:12 UTC
Following #883 we should be able to type check generated BIR.

**Comment by manuranga** [comment] 2023-02-21 09:59
This is duplicate of #1022
It has two parts, flow part and local part. Flow part is already covered by #1026
I didn't implement the local part, it's supposed to be covered by Ushera's work, but we abandonet that effort.
I think it's better to close this and assign yourself  #1022.

**Closed as completed** 2023-02-22 02:06 UTC
