### ISSUE TITLE
Generic array type support 

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#129] opened 2021-02-25 08:26 UTC
**Description:**
Add support for generic array type support 

**Suggested Labels:**

Type/Feature

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Kishanthan** [comment] 2021-02-27 08:59
Closing this as a duplicate of https://github.com/ballerina-platform/nballerina/issues/124

**Closed by Kishanthan** 2021-02-27 08:59 UTC
