### ISSUE TITLE
Change syntaxNodeToWords to iterative instead recursive

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#989] opened 2022-04-06 04:59 UTC
I am getting following fail when running my fork in GitHub.

```
		[fail] testParserOnTestSuite#'13-intsubtype/enumbyte-v.bal':

		    java.lang.StackOverflowError

		    	at java.util.Arrays:hashCode(Arrays.java:4685)
		    	java.util.Objects:hash(Objects.java:146)
		    	io.ballerina.runtime.internal.types.BType:<init>(BType.java:50)
		    	io.ballerina.runtime.internal.types.BAnnotatableType:<init>(BAnnotatableType.java:39)
		    	io.ballerina.runtime.internal.types.BErrorType:<init>(BErrorType.java:42)
		    	io.ballerina.runtime.internal.values.ErrorValue:<init>(ErrorValue.java:87)
		    	io.ballerina.runtime.api.creators.ErrorCreator:createError(ErrorCreator.java:62)
		    	io.ballerina.runtime.internal.ErrorUtils:createInteropError(ErrorUtils.java:80)
		    	ballerina.lang.array.0:externNext(internal:35)
		    	ballerina.lang.array.0.$value$ArrayIterator:next(internal:31)
		    	ballerina.lang.array.0.$value$ArrayIterator:call(internal:-1)
		    	wso2.nballerina.front.syntax.0:syntaxNodeToWords(syntaxNode:659)
		    	wso2.nballerina.front.syntax.0:syntaxNodeToWords(syntaxNode:687)
		    	wso2.nballerina.front.syntax.0:syntaxNodeToWords(syntaxNode:687)
                        ....
 		    	wso2.nballerina.front.syntax.0:syntaxNodeToWords(syntaxNode:687)
		    	wso2.nballerina.front.syntax.0:syntaxNodeToString(syntaxNode:649)
		    	wso2.nballerina.front.syntax.0.tests.testParserOnTestSuite:partToLines(tests-testParserOnTestSuite:59)
		    	wso2.nballerina.front.syntax.0.tests.testParserOnTestSuite:testParserOnTestSuite(tests-testParserOnTestSuite:44)
		    	jdk.internal.reflect.GeneratedMethodAccessor15:invoke(unknown-source:-1)
		    	jdk.internal.reflect.DelegatingMethodAccessorImpl:invoke(DelegatingMethodAccessorImpl.java:43)
		    	java.lang.reflect.Method:invoke(Method.java:566)
		    	org.ballerinalang.test.runtime.entity.TesterinaFunction:lambda$runOnSchedule$0(TesterinaFunction.java:108)
		    	io.ballerina.runtime.internal.scheduling.SchedulerItem:execute(Scheduler.java:611)
		    	io.ballerina.runtime.internal.scheduling.Scheduler:run(Scheduler.java:317)
		    	io.ballerina.runtime.internal.scheduling.Scheduler:runSafely(Scheduler.java:284)
		    	java.lang.Thread:run(Thread.java:834)

```

**Comment by jclark** [comment] 2022-04-06 05:05
This is a duplicate of #988.

The problem seems to me to be that our syntax tree is representing a flat source structure using a deeply nested syntax tree.

**Closed as completed** 2022-04-06 05:08 UTC
Labels: duplicate, optimization
